Lab2_MVC_MamaniAyalaBrandon/Models/ClsBillete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_MVC_MamaniAyalaBrandon.Models
{
    public class ClsBillete
    {
        public int monto { get; set; }
        public int b100 { get; set; }
        public int b50 { get; set; }
        public int b20 { get; set; }
        public int b10 { get; set; }

    }
}

Lab2_MVC_MamaniAyalaBrandon/Models/ClsBisiesto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using Lab2_MVC_MamaniAyalaBrandon.Models;

namespace Lab2_MVC_MamaniAyalaBrandon.Models
{
    public class ClsBisiesto
    {
        public int Inicio { get; set; }
        public int Fin { get; set; }
        public string Bisiesto { get; set; }
        public string Nobisiesto { get; set; }
        public string Todo { get; set; }
        public string Resultado { get; set; }
    }
}

Lab2_MVC_MamaniAyalaBrandon/Models/ClsPersona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Lab2_MVC_MamaniAyalaBrandon.Models
{
    public class ClsPersona
    {
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string email { get; set; } 
        public bool sexo { get; set; }
        public double altura { get; set; }
        public  int edad { get; set; }
    }
}

Lab2_MVC_MamaniAyalaBrandon/Models/ClsTest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_MVC_MamaniAyalaBrandon.Models
{
    public class ClsTest
    {
        public int atributo1 { get; set; }
    }
}

Lab2_MVC_MamaniAyalaBrandon/Controllers/BilleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Lab2_MVC_MamaniAyalaBrandon.Models;

namespace Lab2_MVC_MamaniAyalaBrandon.Controllers
{
    public class BilleteController : Controller
    {
        // GET: Billete
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Viualizar(ClsBillete objBillete) {

            int cantidad;
            cantidad = objBillete.monto;

            int cant100, cant50, cant20, cant10;
            int res100, res50, res20, res10;

            cant100 = cantidad / 100;
            res100 = cantidad % 100;

            cant50 = res100 / 50;
            res50 = res100 % 50;

            cant20 = res50 / 20;
            res20 = res50 % 20;

            cant10 = res20 / 10;
            res10 = res20 % 10;

            objBillete.b100 = cant100;
            objBillete.b50 = cant50;
            objBillete.b20 = cant20;
            objBillete.b10 = cant10;

            return View(objBillete);
        }
    }
}

Lab2_MVC_MamaniAyalaBrandon/Controllers/BisiestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_MVC_MamaniAyalaBrandon.Models;

namespace Lab2_MVC_MamaniAyalaBrandon.Controllers
{
    public class BisiestoController : Controller
    {
        // GET: Bisiesto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Mostrar(ClsBisiesto ObjBisiesto) {

            ObjBisiesto.Bisiesto = " ";
            ObjBisiesto.Nobisiesto = " ";
            ObjBisiesto.Resultado = " ";
            ObjBisiesto.Inicio = Convert.ToInt32(Request.Form["Inicio"]);
            ObjBisiesto.Fin = Convert.ToInt32(Request.Form["Fin"]);

            for (int i = ObjBisiesto.Inicio; i <= ObjBisiesto.Fin; i++) {
                ObjBisiesto.Todo += i + ", ";
                if (i % 400 == 0)
                {
                    ObjBisiesto.Bisiesto = ObjBisiesto.Bisiesto + i + "\n";
                }
                else if (i % 4 == 0 && i % 400 == 0 && i % 100 != 0)
                {
                    ObjBisiesto.Bisiesto = i + "\n";
                }
                else
                {
                    ObjBisiesto.Nobisiesto += i + "\n";
                }
            }
            string Tipo = Request.Form["Anio"];
            if (Tipo == "Bisiestos") { ObjBisiesto.Resultado = ObjBisiesto.Bisiesto; }
            else if (Tipo == "No Bisiestos") { ObjBisiesto.Resultado = ObjBisiesto.Nobisiesto; }
            else if (Tipo == "Ambos") { ObjBisiesto.Resultado = ObjBisiesto.Todo; }
            
            
            return View(ObjBisiesto);
        }
    }
}

Lab2_MVC_MamaniAyalaBrandon/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Lab2_MVC_MamaniAyalaBrandon.Models;


namespace Lab2_MVC_MamaniAyalaBrandon.Controllers
{
    public class PersonaController : Controller
    {
        List<ClsPersona> obj_Lista_Persona = new List<ClsPersona>();

        // GET: Persona
        public ActionResult Index()
        {
          
            //Se instancia con persona1
            ClsPersona objPersona1 = new ClsPersona
            {
                //Instanciar los atributos de la clase
                apellido = "Mamani Ayala",
                nombre = "Brandon",
                email = "bramamania@upt.pe",
                sexo = true,
                edad = 22,
                altura = 1.71
            };
            //Pasar el objeto al objeto lista
            obj_Lista_Persona.Add(objPersona1);

            ClsPersona objPersona2 = new ClsPersona
            {
                apellido = "Sosa Bedoya",
                nombre = "Sharon",
                email = "sharon123@hotmail.com",
                sexo = false,
                edad = 21,
                altura =1.61
            };

            obj_Lista_Persona.Add(objPersona2);

            ClsPersona objPersona3 = new ClsPersona
            {
                apellido = "Ordoñez Quilli",
                nombre = "Ronald",
                email = "ron123@hotmail.com",
                sexo = true,
                edad = 25,
                altura = 1.75
            };

            obj_Lista_Persona.Add(objPersona3);



            return View(obj_Lista_Persona);
        }
    }
}

Lab2_MVC_MamaniAyalaBrandon/Views/Billete/Index.cshtml
@model Lab2_MVC_MamaniAyalaBrandon.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
         <center>
             <h1><b>Cajero de Billetes</b></h1><br />

             @using (Html.BeginForm("Viualizar","Billete",FormMethod.Post)) { 

                 <div>
                     @Html.LabelFor(model => model.monto, "Ingrese Monto: ")
                     @Html.EditorFor(model => model.monto)
                 </div><br />
                 <input type="submit" value="Cambiar"/>
             }
         </center>
    </div>
</body>
</html>

Lab2_MVC_MamaniAyalaBrandon/Views/Billete/Viualizar.cshtml
@model Lab2_MVC_MamaniAyalaBrandon.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Viualizar</title>
</head>
<body>
    <div> 
        <center>
            <h1>Cambio</h1><br />
                           <div>
                               <label>Monto: @Model.monto</label><br />
                               <label>Billetes de 100: @Model.b100</label><br />
                               <label>Billetes de 50: @Model.b50</label><br />
                               <label>Biletes de 20: @Model.b20</label><br />
                               <label>Billetes de 10: @Model.b10</label><br />
                           </div>
                <br /><a href="Index"> << Retornar</a>
        </center>
    </div>
</body>
</html>

Lab2_MVC_MamaniAyalaBrandon/Views/Bisiesto/Index.cshtml
@model Lab2_MVC_MamaniAyalaBrandon.Models.ClsBisiesto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <center>
            <h1><b>Años Bisiestos y no bisiestos</b></h1><br />
                 <div>
                     @using (Html.BeginForm("Mostrar", "Bisiesto", FormMethod.Post))
                      {
                        <div>
                            @Html.LabelFor(model => model.Inicio ,"Año inicial: ")
                            @Html.TextBoxFor(model => model.Inicio)
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Fin ,"Año final: ")
                            @Html.TextBoxFor(model => model.Fin)
                        </div>
                        <div>
                            <h3>Opciones: </h3>
                            <br />
                            <label>
                                @Html.RadioButton("Anio", "Bisiestos", true)<label>Bisiestos</label>
                            </label>
                            <label>
                                @Html.RadioButton("Anio", "No Bisiestos", true) <label>No Bisiestos</label>
                            </label>
                            <label>
                                @Html.RadioButton("Anio", "Ambos", true) <label>Ambos</label>
                            </label>
                        </div>
                        <br /><br />
                        <input type="submit" value="Generar" />
                       }
                  </div>
        </center>
    </div>
</body>
</html>

Lab2_MVC_MamaniAyalaBrandon/Views/Bisiesto/Mostrar.cshtml
@model Lab2_MVC_MamaniAyalaBrandon.Models.ClsBisiesto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Mostrar</title>
</head>
<body>
    <div>
        <h1>Años Bisiestos y No Bisiestos</h1><br />

        <h2><strong>@Request["Anio"]</strong></h2>
            <div>
                <strong>@Model.Resultado</strong>
            </div>
        <br /><a href="Index"> << Retornar</a>
    </div>
</body>
</html>

Lab2_MVC_MamaniAyalaBrandon/Views/Persona/Index.cshtml
@model IEnumerable<Lab2_MVC_MamaniAyalaBrandon.Models.ClsPersona>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <center>
            <h1><b>Lista de Personas</b></h1><br />
            <table border="1">
                <thead>
                    <tr>
                        <th>Apellidos</th>
                        <th>Nombres</th>
                        <th>Email</th>
                        <th>Sexo</th>
                        <th>Edad</th>
                        <th>Altura</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.apellido)</td>
                        <td>@Html.DisplayFor(modelItem => item.nombre)</td>
                        <td>@Html.DisplayFor(modelItem => item.email)</td>
                        <td>@Html.DisplayFor(modelItem => item.sexo)</td>
                        <td>@Html.DisplayFor(modelItem => item.edad)</td>
                        <td>@Html.DisplayFor(modelItem => item.altura)</td>
                    </tr>
                    }
                </tbody>
            </table>
        </center>
    </div>
</body>
</html>